server:
  port: 4000
spring:
  security:
    oauth2:
      client:
        registration:
          myoauth2:
            provider: spring
            client-id: ${OAUTH_CLIENTID}
            client-secret: ${OAUTH_SECRET}
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:4000/auth/provider/callback
        provider:
          spring:
            issuer-uri: ${OAUTH_ISSUER_URI}
