server:
  port: 4000
spring:
  security:
    oauth2:
      client:
        registration:
          myoauth2:
            provider: spring
            client-id: ${OAUTH_CLIENTID}
            client-secret: ${OAUTH_SECRET}
            scope: ${OAUTH_SCOPE}
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_REDIRECT_URI}
        provider:
          spring:
            issuer-uri: ${OAUTH_ISSUER_URI}
